# Generated by Django 4.0.5 on 2022-08-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='like',
        ),
    ]
