# Generated by Django 4.0.5 on 2022-08-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_commentpost_dislike_remove_commentpost_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
